// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycpikrcznwyfuknwtkgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcGlrcmN6bnd5ZnVrbnd0a2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTIwMDYsImV4cCI6MjA2NjY4ODAwNn0.RcLH6UAc0on9CpfqrnKKl8Utk9th9MNe5x6XnQbvfnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);